import { addIcons } from 'oh-vue-icons'
import {
  FaFacebook as Facebook,
  FaTwitter as Twitter,
  RiInstagramFill as Instagram,
  RiAppsLine as App,
  RiMenuFoldLine as MenuFold,
  RiMenuUnfoldLine as MenuUnfold,
  BiCart3 as Cart,
  MdAttachmoney as Money,
  HiChevronDown as ChevronDown,
  HiChevronUp as ChevronUp,
  RiHome4Line as HomeIcon,
  HiUserCircle as UserIcon,
  BiPersonWorkspace as PersonWIcon,
  BiPersonPlus as PersonPlusIcon,
  BiPersonRolodex as PersonRIcon,
  HiUserGroup as UserGroupIcon,
  CoSettings as SettingsIcon,
  HiUser,
  RiLock2Line,
  FaRegularUser,
  BiEye,
  BiEyeSlash,
  MdEmailOutlined,
  BiChatLeftText,
  MdNotifications,
  PrPowerOff,
  BiArrowCounterclockwise,
  CoSettings,
  BiSearch,
  BiArrowUp,
  BiArrowDown,
  BiArrowDownUp,
  MdFilterlistRound,
  PrCloudDownload,
  MdRemoveredeyeOutlined,
  MdAdd,
  LaEdit,
  BiTrash3,
  FaTachometerAlt,
  HiSolidUserGroup,
  LaGraduationCapSolid,
  FaGraduationCap,
  LaFileInvoiceDollarSolid,
  FaUmbrellaBeach,
  FaUserClock,
  MdPersonsearch,
  FaFileSignature,
  FaBullhorn,
  MdNotificationaddRound,
  FaUserCircle,
  IoSettingsSharp,
  CoCalendar,
  FaCalendarAlt
} from 'oh-vue-icons/icons'

addIcons(
  Facebook,
  Twitter,
  Instagram,
  App,
  MenuFold,
  MenuUnfold,
  Cart,
  Money,
  ChevronDown,
  ChevronUp,
  HomeIcon,
  UserIcon,
  PersonWIcon,
  PersonPlusIcon,
  PersonRIcon,
  UserGroupIcon,
  SettingsIcon,
  HiUser,
  RiLock2Line,
  FaRegularUser,
  BiEye,
  BiEyeSlash,
  MdEmailOutlined,
  BiChatLeftText,
  MdNotifications,
  PrPowerOff,
  BiArrowCounterclockwise,
  CoSettings,
  BiSearch,
  BiArrowUp,
  BiArrowDown,
  BiArrowDownUp,
  MdFilterlistRound,
  PrCloudDownload,
  MdRemoveredeyeOutlined,
  MdAdd,
  LaEdit,
  BiTrash3,
  FaTachometerAlt,
  HiSolidUserGroup,
  LaGraduationCapSolid,
  FaGraduationCap,
  LaFileInvoiceDollarSolid,
  FaUmbrellaBeach,
  FaUserClock,
  MdPersonsearch,
  FaFileSignature,
  FaBullhorn,
  MdNotificationaddRound,
  FaUserCircle,
  IoSettingsSharp,
  CoCalendar,
  FaCalendarAlt
)

const icons = {
  App: 'ri-apps-line',
  Facebook: 'fa-facebook',
  Twitter: 'fa-twitter',
  Instagram: 'ri-instagram-fill',
  MenuFold: 'ri-menu-fold-line',
  MenuUnfold: 'ri-menu-unfold-line',
  Cart: 'bi-cart3',
  Money: 'md-attachmoney',
  ChevronDown: 'hi-chevron-down',
  ChevronUp: 'hi-chevron-up',
  Home: 'ri-home-4-line',
  User: 'hi-user-circle',
  PersonW: 'bi-person-workspace',
  PersonPlus: 'bi-person-plus',
  PersonR: 'bi-person-rolodex',
  UserGroup: 'hi-user-group',
  Settings: 'co-settings',
  FormUNIcon: 'fa-regular-user',
  FormPWIcon: 'ri-lock-2-line',
  FormPWShowIcon: 'bi-eye',
  FormPWHideIcon: 'bi-eye-slash',
  FormEmailIcon: 'md-email-outlined',
  FormMsgIcon: 'bi-chat-left-text',
  NotifIcon: 'md-notifications',
  SignOutIcon: 'pr-power-off',
  RefreshIcon: 'bi-arrow-counterclockwise',
  SettingsIcon: 'co-settings',
  UserSearch: 'bi-search',
  SortIcon: 'bi-arrow-down-up',
  SortAscIcon: 'bi-arrow-up',
  SortDescIcon: 'bi-arrow-down',
  FilterIcon: 'md-filterlist-round',
  ExportIcon: 'pr-cloud-download',
  ViewIcon: 'md-removeredey-outlined',
  AddIcon: 'md-add',
  EditIcon: 'la-edit',
  DeleteIcon: 'bi-trash3',
  TachometerIcon: 'fa-tachometer-alt',
  HiSolidUserGroup: 'hi-solid-user-group',
  GraduationCapIcon: 'la-graduation-cap-solid',
  GraduationCap: 'fa-graduation-cap',
  InvoiceIcon: 'la-file-invoice-dollar-solid',
  FaUmbrellaBeach: 'fa-umbrella-beach',
  FaUserClock: 'fa-user-clock',
  MdPersonsearch: 'md-personsearch',
  FaFileSignature: 'fa-file-signature',
  FaBullhorn: 'fa-bullhorn',
  MdNotificationaddRound: 'md-notificationadd-round',
  FaUserCircle: 'fa-user-circle',
  IoSettingsSharp: 'io-settings-sharp',
  CoCalendar: 'co-calendar',
  FaCalendarAlt: 'fa-calendar-alt'
}

export { icons }
