import { addIcons } from 'oh-vue-icons'
import {
  FaFacebook as Facebook,
  FaTwitter as Twitter,
  RiInstagramFill as Instagram,
  RiAppsLine as App,
  RiMenuFoldLine as MenuFold,
  RiMenuUnfoldLine as MenuUnfold,
  BiCart3 as Cart,
  MdAttachmoney as Money,
  HiChevronDown as ChevronDown,
  HiChevronUp as ChevronUp,
  RiHome4Line as HomeIcon,
  HiUserCircle as UserIcon,
  BiPersonWorkspace as PersonWIcon,
  BiPersonPlus as PersonPlusIcon,
  BiPersonRolodex as PersonRIcon,
  HiUserGroup as UserGroupIcon,
  CoSettings as SettingsIcon,
  HiUser,
  RiLock2Line,
  FaRegularUser,
  BiEye,
  BiEyeSlash,
  MdEmailOutlined,
  BiChatLeftText,
  MdNotifications,
  PrPowerOff,
  BiArrowCounterclockwise,
  CoSettings,
  BiSearch,
  BiArrowUp,
  BiArrowDown,
  BiArrowDownUp,
  MdFilterlistRound,
  PrCloudDownload,
  MdRemoveredeyeOutlined,
  MdAdd,
  LaEdit,
  BiTrash3,
  FaTachometerAlt,
  HiSolidUserGroup,
  LaGraduationCapSolid,
  FaGraduationCap,
  LaFileInvoiceDollarSolid,
  FaUmbrellaBeach,
  FaUserClock,
  MdPersonsearch,
  FaFileSignature,
  FaBullhorn,
  MdNotificationaddRound,
  FaUserCircle,
  IoSettingsSharp,
  CoCalendar,
  FaCalendarAlt,
  CoPrint,
  BiPaperclip,
  HiTable,
  FaMoneyBill,
  FaDollarSign,
  FaMinusCircle,
  FaBell,
  FaMoneyCheck,
  FaBed,
  FaBook,
  FaUserGraduate,
  FaChartBar,
  FaBullseye,
  FaChartLine,
  FaUser,
  FaUserTag,
  FaExclamationTriangle,
  FaHandHoldingUsd,
  FaAward,
  FaCompass,
  FaBuilding,
  FaUserFriends,
  FaLayerGroup,
  FaBriefcase,
  FaFileAlt,
  FaIndustry,
  FaCertificate,
  FaMoneyCheckAlt,
  FaRegularCalendarAlt,
  FaUserTimes,
  FaUniversity,
  FaCogs,
  FaSlidersH,
  FaSitemap,
  FaRegularChartBar,
  FaMoneyBillWave,
  FaRuler,
  FaCalendarCheck,
  FaChartArea,
  FaFlag,
  FaUsers,
  FaEnvelope,
  FaCalculator,
  FaFlask,
  FaChalkboardTeacher,
  FaNewspaper,
  FaComments,
  MdLocalphone,
  FaDashcube,
  FaInfo,
  FaFilePdf,
  FaStore,
  FaFileContract,
  FaGavel,
  FaPencilAlt,
  FaChartPie,
  FaMapMarked,
  GiBullHorns,
  PrChartLine,
  BiPlusCircle,
  FaLifeRing,
  FaCubes,
  FaArrowUp,
  FaArrowDown,
  FaFile,
  FaClipboardList,
  FaTags,
  fafilea


  






} from 'oh-vue-icons/icons'

addIcons(
  Facebook,
  Twitter,
  Instagram,
  App,
  MenuFold,
  MenuUnfold,
  Cart,
  Money,
  ChevronDown,
  ChevronUp,
  HomeIcon,
  UserIcon,
  PersonWIcon,
  PersonPlusIcon,
  PersonRIcon,
  UserGroupIcon,
  SettingsIcon,
  HiUser,
  RiLock2Line,
  FaRegularUser,
  BiEye,
  BiEyeSlash,
  MdEmailOutlined,
  BiChatLeftText,
  MdNotifications,
  PrPowerOff,
  BiArrowCounterclockwise,
  CoSettings,
  BiSearch,
  BiArrowUp,
  BiArrowDown,
  BiArrowDownUp,
  MdFilterlistRound,
  PrCloudDownload,
  MdRemoveredeyeOutlined,
  MdAdd,
  LaEdit,
  BiTrash3,
  FaTachometerAlt,
  HiSolidUserGroup,
  LaGraduationCapSolid,
  FaGraduationCap,
  LaFileInvoiceDollarSolid,
  FaUmbrellaBeach,
  FaUserClock,
  MdPersonsearch,
  FaFileSignature,
  FaBullhorn,
  MdNotificationaddRound,
  FaUserCircle,
  IoSettingsSharp,
  CoCalendar,
  FaCalendarAlt,
  CoPrint,
  BiPaperclip,
  HiTable,
  FaMoneyBill,
  FaDollarSign,
  FaMinusCircle,
  FaBell,
  FaMoneyCheck,
  FaBed,
  FaBook,
  FaUserGraduate,
  FaChartBar,
  FaBullseye,
  FaChartLine,
  FaUser,
  FaUserTag,
  FaExclamationTriangle,
  FaHandHoldingUsd,
  FaAward,
  FaCompass,
  FaBuilding,
  FaUserFriends,
  FaLayerGroup,
  FaBriefcase,
  FaFileAlt,
  FaIndustry,
  FaCertificate,
  FaMoneyCheckAlt,
  FaRegularCalendarAlt,
  FaUserTimes,
  FaUniversity,
  FaCogs,
  FaSlidersH,
  FaSitemap,
  FaRegularChartBar,
  FaMoneyBillWave,
  FaRuler,
  FaCalendarCheck,
  FaChartArea,
  FaFlag,
  FaUsers,
  FaEnvelope,
  FaCalculator,
  FaFlask,
  FaChalkboardTeacher,
  FaNewspaper,
  FaComments,
  MdLocalphone,
  FaDashcube,
  FaInfo,
  FaFilePdf,
  FaStore,
  FaFileContract,
  FaGavel,
  FaPencilAlt,
  FaChartPie,
  FaMapMarked,
  GiBullHorns,
  PrChartLine,
  BiPlusCircle,
  FaLifeRing;
  fa-cubes







)

const icons = {
  App: 'ri-apps-line',
  Facebook: 'fa-facebook',
  Twitter: 'fa-twitter',
  Instagram: 'ri-instagram-fill',
  MenuFold: 'ri-menu-fold-line',
  MenuUnfold: 'ri-menu-unfold-line',
  Cart: 'bi-cart3',
  Money: 'md-attachmoney',
  ChevronDown: 'hi-chevron-down',
  ChevronUp: 'hi-chevron-up',
  Home: 'ri-home-4-line',
  User: 'hi-user-circle',
  PersonW: 'bi-person-workspace',
  PersonPlus: 'bi-person-plus',
  PersonR: 'bi-person-rolodex',
  UserGroup: 'hi-user-group',
  Settings: 'co-settings',
  FormUNIcon: 'fa-regular-user',
  FormPWIcon: 'ri-lock-2-line',
  FormPWShowIcon: 'bi-eye',
  FormPWHideIcon: 'bi-eye-slash',
  FormEmailIcon: 'md-email-outlined',
  FormMsgIcon: 'bi-chat-left-text',
  NotifIcon: 'md-notifications',
  SignOutIcon: 'pr-power-off',
  RefreshIcon: 'bi-arrow-counterclockwise',
  SettingsIcon: 'co-settings',
  UserSearch: 'bi-search',
  SortIcon: 'bi-arrow-down-up',
  SortAscIcon: 'bi-arrow-up',
  SortDescIcon: 'bi-arrow-down',
  FilterIcon: 'md-filterlist-round',
  ExportIcon: 'pr-cloud-download',
  ViewIcon: 'md-removeredey-outlined',
  AddIcon: 'md-add',
  EditIcon: 'la-edit',
  DeleteIcon: 'bi-trash3',
  TachometerIcon: 'fa-tachometer-alt',
  HiSolidUserGroup: 'hi-solid-user-group',
  GraduationCapIcon: 'la-graduation-cap-solid',
  GraduationCap: 'fa-graduation-cap',
  InvoiceIcon: 'la-file-invoice-dollar-solid',
  FaUmbrellaBeach: 'fa-umbrella-beach',
  FaUserClock: 'fa-user-clock',
  MdPersonsearch: 'md-personsearch',
  FaFileSignature: 'fa-file-signature',
  FaBullhorn: 'fa-bullhorn',
  MdNotificationaddRound: 'md-notificationadd-round',
  FaUserCircle: 'fa-user-circle',
  IoSettingsSharp: 'io-settings-sharp',
  CoCalendar: 'co-calendar',
  FaCalendarAlt: 'fa-calendar-alt',
  CoPrint: 'co-print',
  BiPaperclip: 'bi-paperclip',
  HiTable: 'hi-table',
  FaMoneyBill: 'fa-money-bill',
  FaDollarSign:'fa-dollar-sign',
  FaMinusCircle: 'fa-minus-circle',
  FaBell: 'fa-bell',
  FaMoneyCheck: 'fa-money-check',
  FaBed: 'fa-bed',
  FaBook: 'fa-book',
  FaUserGraduate: 'fa-user-graduate',
  FaChartBar: 'fa-chart-bar',
  FaBullseye: 'fa-bullseye',
  FaChartLine: 'fa-chart-line',
  FaUser: 'fa-user',
  FaUserTag: 'fa-user-tag',
  FaExclamationTriangle: 'fa-exclamation-triangle',
  FaHandHoldingUsd: 'fa-hand-holding-usd',
  FaAward: 'fa-award',
  FaCompass: 'fa-compass',
  FaBuilding: 'fa-building',
  FaUserFriends: 'fa-user-friends',
  FaLayerGroup: 'fa-layer-group',
  FaBriefcase: 'fa-briefcase',
  FaFileAlt: 'fa-file-alt',
  FaIndustry: 'fa-industry',
  FaCertificate: 'fa-certificate',
  FaMoneyCheckAlt: 'fa-money-check-alt',
  FaRegularCalendarAlt: 'fa-regular-calendar-alt',
  FaUserTimes: 'fa-user-times',
  FaUniversity: 'fa-university',
  FaCogs: 'fa-cogs',
  FaSlidersH: 'fa-sliders-h',
  FaSitemap: 'fa-sitemap',
  FaRegularChartBar: 'fa-regular-chart-bar',
  FaMoneyBillWave: 'fa-money-bill-wave',
  FaRuler: 'fa-ruler',
  FaCalendarCheck: 'fa-calendar-check',
  FaChartArea: 'fa-chart-area',
  FaFlag: 'fa-flag',
  FaUsers: 'fa-users',
  FaEnvelope: 'fa-envelope',
  FaCalculator: 'fa-calculator',
  FaFlask: 'fa-flask',
  FaChalkboardTeacher: 'fa-chalkboard-teacher',
  FaNewspaper: 'fa-newspaper',
  FaComments: 'fa-comments',
  FaPhone: 'fa-phone',
  MdLocalphone: 'md-localphone',
  FaDashcube: 'fa-dashcube',
  FaInfo:'fa-info',
  FaFilePdf: 'fa-file-pdf',
  FaStore:'fa-store',
  FaFileContract: 'fa-file-contract',
  FaGavel: 'fa-gavel',
  FaPencilAlt: 'fa-pencil-alt',
  FaChartPie: 'fa-chart-pie',
  FaMapMarked: 'fa-map-marked',
  GiBullHorns: 'gi-bull-horns',
  PrChartLine: 'pr-chart-line',
  BiPlusCircle: 'bi-plus-circle',
  FaLifeRing: 'fa-life-ring'
  



  
}

export { icons }
